import styled from "styled-components";

export const metadata = {
  title: 'Cornelius Pavlic',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body style={{background:'#35155D'}}>{children}</body>
    </html>
  )
}
